# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

require 'yaml'

# Load local settings from settings.yml file
if File.exist?("settings.yml")
  settings = YAML.load_file('settings.yml')["vagrant"]
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box     = "centos-6.4-base"
  config.vm.box_url = "http://dev.nemac.org/boxes/CentOS-6.4-base.box"

  config.vm.synced_folder "../puppet", "/etc/puppet/files"

  config.vm.provision :shell, :path => "../shell/bootstrap.sh"

  config.vm.provision :puppet do |puppet|
    puppet.options        = "--debug"
    puppet.module_path    = "../puppet/modules"
    puppet.manifests_path = "../puppet"
    puppet.manifest_file  = "geoprocessing-server.pp"
  end

  config.vm.network :forwarded_port, guest: 80, host: settings["web_port"], auto_correct: true

  if settings["additional_port_mappings"]
    settings["additional_port_mappings"].each do |mapping|
      config.vm.network :forwarded_port, guest: mapping["guest_port"], host: mapping["host_port"]
    end
  end

  if settings["private_network_ip"]
    config.vm.network :private_network, ip: settings["private_network_ip"]
  end

  # use a private IP address for virtualbox VMs
  #config.vm.network :private_network, ip: "192.168.33.20"

end
